### ISSUE TITLE
false error for type modifier on import names

### ISSUE THREAD

**Issue by bhvngt** [ota-meshi/eslint-plugin-svelte#137]
While migrating from svelte3, it shows false error for type modifier imports that are combined with regular imports. From [typescript 4.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names) onwards, type imports can be combined with regular imports.

![Screenshot 2022-05-10 at 11 43 47 AM](https://user-images.githubusercontent.com/79074469/167560372-eb5bcf7e-cc80-4323-9fcf-dcf8d8195b49.png)

**Comment by bhvngt** [comment]
Thanks @ota-meshi. I can confirm that #137 and #136 are resolved and working well. Thank you very much for this plugin. Its working quiet well for me.

**Comment by ota-meshi** [comment]
Thanks for letting me know! I'm glad it working for you. If you have any problems, feel free to open an issue.
