### ISSUE TITLE
indent rule requires that <script> elements be indented

### ISSUE THREAD

**Issue by tivac** [ota-meshi/eslint-plugin-svelte#155]
This is how I want to write our svelte components:

```svelte
<script>
const foo = "bar";
</script>
```

But if I enable the indent rule, it really wants me to do this:

```svelte
<script>
    const foo = "bar";
</script>
```

I can disable it using `{ ignoredNodes : [ "SvelteScriptElement" ] }` but it means that none of the indentation for any direct children will be checked, which is kind of a bummer. I'm sure this is a bit annoying of an ask, but would you be open to adding a new option where a user can define the level of indentation they want specifically for `<script>`s? It could default to `1`, so it wouldn't be a breaking change.

If you're open to this proposal I'd be thrilled to figure out how to send a PR for it.

**Comment by ota-meshi** [comment]
Yeah. Adding option to the indent rule sounds good to me.

I think it makes sense to add an option like `indentScriptAndStyle: boolean`.
I think it's easy for users to understand because it's similar to the option in prettier-plugin-svelte.
https://github.com/sveltejs/prettier-plugin-svelte#svelte-indent-script-and-style

**Comment by tivac** [comment]
I've started working on this, quick question for you @ota-meshi: Is there a way to run just a single test currently? I haven't found one so far and it's making iterating on this a bit slower than I'd like.

**Comment by JounQin** [comment]
@tivac 

https://stackoverflow.com/questions/10832031/how-to-run-a-single-test-with-mocha

**Comment by ota-meshi** [comment]
@tivac  Thank you for working on it!
I usually test one rule using the following command:

```sh
yarn mocha "tests/src/**/indent.ts" --reporter dot --timeout 60000
```

If you want to test only `my-test-input.svelte`, add `my-test-config.json` and save `{"only ": true}`.

**Comment by ota-meshi** [comment]
I have opened a PR to explain how you can test rules. #172

**Comment by tivac** [comment]
I got it running just the one rule, thanks for updating the docs. No matter what I try though I don't seem to be able to get my `indentScript: false` option to persist through all the layers of the testing suite.

https://github.com/ota-meshi/eslint-plugin-svelte/compare/main...tivac:eslint-svelte:indent-script-option

Dropping that there in case you see something obvious, I'll keep bashing my head against it for now.
