### ISSUE TITLE
`no-dupe-style-properties` parse error when empty

### ISSUE THREAD

**Issue by shirotech** [ota-meshi/eslint-plugin-svelte#158]
`@ota-meshi/svelte/no-dupe-style-properties` throws an error:
```sql
TypeError: Cannot read property 'range' of undefined
```

When the attribute is empty, for example:
```html
<div class="navbar-main" id="main-navbar" style="" >
```

**Comment by shirotech** [comment]
Also same error for `@ota-meshi/svelte/no-shorthand-style-property-overrides` as well.

**Comment by ota-meshi** [comment]
Thank you for posting this issue!
It's a bug.
