### ISSUE TITLE
Use CI tools like `changesets` for changelog and releasing

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-svelte#166]
https://github.com/changesets/changesets

Related bot https://github.com/apps/changeset-bot and action https://github.com/changesets/action

An example: https://github.com/import-js/eslint-import-resolver-typescript/pull/118/files

**Comment by JounQin** [comment]
And also these projects seem lack of git hooks tools like [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) + [lint-staged](https://github.com/okonet/lint-staged)?

How do you think of them?

**Comment by ota-meshi** [comment]
I agree to introduce those tools :+1:

**Comment by JounQin** [comment]
@ota-meshi 

I'd like to work on this recently.

A few questions to discuss:

1. Do you want to release npm package manually or by CI automatically instead?
2. Do you have unified configs to be reused for tools like simple-git-hooks and lint-staged? Yours is always preferred here. If not can I use mine at https://github.com/1stG/configs/tree/master/packages Or they should just be used verbose.
3. Do we use https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
4. Do we use https://github.com/remarkjs/remark-lint which can be integrated with ESLint via `eslint-mdx`

**Comment by ota-meshi** [comment]
> Do you want to release npm package manually or by CI automatically instead?

I prefer manually release, but manually release is okay.

I don't know much about other tools as I haven't used them much. I think that it can be adjusted later if there is a problem after introducing it once.

**Comment by JounQin** [comment]
OK, I'll install some GitHub Apps on this repo, it may require you to accept the installation.

**Comment by JounQin** [comment]
@ota-meshi

I found I can not install any GitHub Apps due to lack of permission on a personal repository. 🤣

A GitHub organization is much more suitable for such cases.

Can you help to install them manually?

https://github.com/apps/changeset-bot/installations/new
https://github.com/apps/codesandbox-ci/installations/new
https://github.com/apps/lgtm-com/installations/new

**Comment by ota-meshi** [comment]
I have installed 3 apps into this project and svelte-eslint-parser repo.
Secrets has also been set.
