### ISSUE TITLE
`prefer-style-directive` should be ignored on a component

### ISSUE THREAD

**Issue by shirotech** [ota-meshi/eslint-plugin-svelte#173]
Svelte will throw an error `Style directives cannot be used on components` when it tries to change from `style=` to `style:`

For example:
```svelte
<Component style="display:block"/>
```
will fix to:
```svelte
<Component style:display="block"/>
```

Which will throw an error:
```sql
Style directives cannot be used on components
```

I think this is an obvious issue and doesn't require a reproduction.

**Comment by shirotech** [comment]
Thanks @ota-meshi for the super fast fix! 👍 

Sorry, also just realised this affects `prefer-class-directive` as well.

**Comment by ota-meshi** [comment]
Thank you for let me know.
I can't work today because I have another job today, so could you leave an issue for reminding us?

**Comment by shirotech** [comment]
> I can't work today because I have another job today, so could you leave an issue for reminding us?

Sure, no probs. Thank you so much for your time today, really appreciate it! 👍
