### ISSUE TITLE
Porting some svelte rules I've made elsewhere?

### ISSUE THREAD

**Issue by tivac** [ota-meshi/eslint-plugin-svelte#198]
### Motivation

I've got a collection of custom eslint rules for svelte that I've been iterating on for a while. Now that this package exists (and is excellent!) I'm curious if you'd be interested in PRs to migrate some or all of these rules into this package?

https://github.com/tivac/eslint-plugin-svelte

### Description

- [x] #201 
- [x] #203 
- [x] ~~#205~~
- [x] #206
- [x] #208
- [x] #249
- [x] #211
- [x] #225

### Examples

Examples for all of the rules are available in the [tests folder](https://github.com/tivac/eslint-plugin-svelte/tree/main/tests).

**Comment by ota-meshi** [comment]
That's great for me!!

Are you planning to deprecate `@tivac/eslint-plugin-svelte` after migrating those rules? If so, I have one concern.
`eslint-plugin-svelte` cannot be used with `eslint-plugin-svelte3`.
 `@tivac/eslint-plugin-svelte` can be used with both `eslint-plugin-svelte3` or `eslint-plugin-svelte`.
If we deprecate `@tivac/eslint-plugin-svelte`, it means that those rules cannot be used with `eslint-plugin-svelte3`.

**Comment by ota-meshi** [comment]
By the way, I don't use `eslint-plugin-svelte3`, so it's perfectly fine for me.

**Comment by JounQin** [comment]
I won't consider `eslint-plugin-svelte3` at all personally, it's just full of hacking and unusable for a lot of cases.

**Comment by tivac** [comment]
Oh great, I'll try to get cracking on some PRs then.

I haven't had a ton of issues with `eslint-plugin-svelte3` before but I also see zero reason to use it when this project exists and works great. I will probably remove all of the reactive statement rules from my package I guess? Since the store-focused rules can be used on both `.svelte` and `.js` files I don't know exactly how they'd fit into this package, curious if you have any thoughts there @ota-meshi :)

**Comment by ota-meshi** [comment]
I think it's okay that the plugin contains rules that can also be used with `*.js`.

However, maybe something needs to be done to get the demo for `*.js` to work on the documentation site.

**Comment by baseballyama** [comment]
Thank you for following up on the issue @ota-meshi and @tivac .
Can we close this issue? (I don't have such an ability.)

**Comment by ota-meshi** [comment]
Yeah, thanks to your help, all the rules have been implemented! So I close this issue.
