### ISSUE TITLE
Not compatible with eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by hgiesel** [ota-meshi/eslint-plugin-svelte#199]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.19.0

### What version of `eslint-plugin-svelte` are you using?

2.2.0

### What did you do?

You need a Svelte file with unordered imports in its script component, then execute `eslint --fix`.

### What did you expect to happen?

Would apply the simple-import-sort rules, and sort the imports.

### What actually happened?

It reported no errors

### Link to Minimal Reproducible Example

```javascript
// .eslintrc.js
module.exports = {
    extends: "eslint:recommended",
    parser: "@typescript-eslint/parser",
    parserOptions: {
        extraFileExtensions: [".svelte"],
    },
    plugins: [
        "svelte",
        "simple-import-sort",
        "@typescript-eslint",
    ],
    rules: {
        "no-unused-vars": "off",
        "no-undef": "off",
        "no-redeclare": "off",
        "no-inner-declarations": "off",
        "no-self-assign": "off",
    },
    overrides: [
        {
            files: "**/*.svelte",
            parser: "svelte-eslint-parser",
            parserOptions: {
                parser: "@typescript-eslint/parser",
            },
            rules: {
                "simple-import-sort/imports": "warn",
                "simple-import-sort/exports": "warn",
            },
        },
    ],
    env: { browser: true },
    ignorePatterns: ["backend_proto.d.ts", "*.svelte.d.ts"],
    globals: {
        globalThis: false,
        NodeListOf: false,
    },
};
```

**Comment by ota-meshi** [comment]
Please provide a github repository that can reproduce the problem.

 [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by baseballyama** [comment]
@ToP29  I'm happy if you provide a REPL.

**Comment by ToP29** [comment]
here is [repro](https://github.com/ToP29/eslint-plugin-svelte-import-sort-repro)
you can see for example in file `src\routes\+page.svelte` that import are not sorted
if you use config from `.eslintrc.json - working-sort` and run `npm run lint` then it will sort them. working example uses [eslint-plugin-svelte3](https://www.npmjs.com/package/eslint-plugin-svelte3)

**Comment by baseballyama** [comment]
@ToP29 

Thank you for your REPL.
But you can not use both [eslint-plugin-svelte3](https://www.npmjs.com/package/eslint-plugin-svelte3) and this plugin at the same time.

See: https://github.com/ota-meshi/eslint-plugin-svelte#-attention

**Comment by ToP29** [comment]
You i know, i just created to eslint confings, so you can see it working and broken. if you check [.eslintrc.json](https://github.com/ToP29/eslint-plugin-svelte-import-sort-repro/blob/main/.eslintrc.json) then you will see there is no [eslint-plugin-svelte3](https://www.npmjs.com/package/eslint-plugin-svelte3) installed

**Comment by ota-meshi** [comment]
Thank you for sharing the repository.

eslint-plugin-simple-import-sort doesn't seem to work as you say.
I think this is because eslint-plugin-simple-import-sort only checks import nodes of root level node (Program node).
The result of our parser is that the SvelteScriptElement node has import nodes.

I recommend using `import/order` instead.
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

Or ask eslint-plugin-simple-import-sort to handle imports with anything other than the root node.
Because I have the same problem with typescript.
`import/order` handles the following typescript properly, but eslint-plugin-simple-import-sort does not.

```ts
declare module 'my-module' {
    import type { ParsedPath } from 'path';
    import type { CopyOptions } from 'fs';
}
```

https://github.com/import-js/eslint-plugin-import/blob/c3d14cb920bdc6d277134973d37364db22c3a8b8/tests/src/rules/order.js#L3123-L3140
