### ISSUE TITLE
`no-undefined-in-text-mustaches` rule

### ISSUE THREAD

**Issue by PatrickG** [ota-meshi/eslint-plugin-svelte#217]
### Description

A rule like `no-object-in-text-mustaches` but for variables that *might be* `undefined`.

Related: https://github.com/sveltejs/language-tools/issues/1582

**Comment by ota-meshi** [comment]
Use the template to write details.

https://github.com/ota-meshi/eslint-plugin-svelte/issues/new?assignees=&labels=enhancement%2Cnew+rule&template=new_rule_request.yml
