### ISSUE TITLE
Design adjustment for docs

### ISSUE THREAD

**Issue by baseballyama** [ota-meshi/eslint-plugin-svelte#253]
Now the document site changes background color after scrolling down, this is a bit weird, and maybe a few more design adjustments should do.

Now I have a few ideas, but if you have more ideas, please write comments.

- [ ] Fix background color
- [ ] change header behavior like [SvelteKit web site](https://kit.svelte.dev/)
- [ ] Left side scroll bar's color. (Maybe SvelteKit web site7s color is better?)

**Comment by ota-meshi** [comment]
I'm not particular about the current document design. Making changes for good design is great :+1:

**Comment by baseballyama** [comment]
Already I updated the design for now.
So I close this issue.
If you have some idea for it. Please create a new issue.
