### ISSUE TITLE
Type annotations not working in Svelte's HTML template section

### ISSUE THREAD

**Issue by ptrxyz** [ota-meshi/eslint-plugin-svelte#255]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.23.1

### What version of `eslint-plugin-svelte` are you using?

2.8.0

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
	root: true,
	parser: '@typescript-eslint/parser',
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:@typescript-eslint/recommended-requiring-type-checking',
		'plugin:import/recommended',
		'plugin:import/typescript',
		'plugin:svelte/recommended',
		'plugin:svelte/prettier',
		'prettier'
	],
	plugins: ['unused-imports', '@typescript-eslint', 'import'],
	ignorePatterns: ['*.cjs', 'svelte.config.js', 'tailwind.config.cjs', 'postcss.config.cjs'],
	overrides: [
		{
			files: ['*.svelte'],
			parser: 'svelte-eslint-parser',
			parserOptions: {
				parser: '@typescript-eslint/parser'
			}
		}
	],
	settings: {
		'svelte3/typescript': () => require('typescript'),
		'import/resolver': { typescript: {} },
		'import/parsers': { '@typescript-eslint/parser': ['.ts', '.tsx'] }
	},
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2020,
		project: ['./tsconfig.json'],
		extraFileExtensions: ['.svelte']
	},
	env: {
		browser: true,
		es2017: true,
		node: true
	},
	rules: {
		'no-unused-vars': 'off',
		'@typescript-eslint/no-unused-vars': 'off',
		'unused-imports/no-unused-vars': [
			'warn',
			{ vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' }
		],
		'unused-imports/no-unused-imports': 'error'
	}
}

```
</details>

```svelte
<script lang="ts">
// this works:
const something = (e:any) => e
</script>

<!-- this does not -->
<div on:click={(e : any) => e}>Click</div>
```

### What did you expect to happen?

I expect `on:click={(e : any) => e}` on the `div` to work.

### What actually happened?

eslint complains that the `:` would be an unexpected token. As soon as I remove the type annotations, things work great.

```
Parsing error: Unexpected token (eslint)
```

### Link to Minimal Reproducible Example

[EXAMPLE](https://ota-meshi.github.io/eslint-plugin-svelte/playground/#eJx1Wcuu3DYS/ZWeu5oAIQLM0ojzG7PxhpKqu5lLkTJJ3b4dw/+eU3xTLcMw3Koqvupx6pD+8Tbbhd6+vP35HyEu/yc925UuwV7Ia2WC2PR+U0b4D9KBLkL89c386WentnDR0ty+fnsL/tsbpJfLbI0PF4/x4a7M7fL18l/6cpHm+dvl618XwsA/0khY42PaQ7DmYs2XWav5/euPzpp+fjNvv7+5XZN/+/LjLS3/h7Fi2TcSpD0JdRWTtvM7DP73+9HCh6cmsTm7kQuKXmyeRq5qFl7bIPCTDnoD8XU3c1DWiLs0iyZ3MLHT3zQHAd8E+gxi3X2Q8/1lJX+3LvAM45aewn6Qc2p5HRCsIyH908wHzW7ejX2YPNGiHNZXH23K3vxDarUIxHJT+ng4GcQ9rFoEeTsuHqS7UYBfpXnvVSlW8IQX4bmdTLjQtN/OZnQk0y6LO39poFUgJ/VRv5vd05ITUKibgXuOJp6QJ/48Bo6+73CVsFtQq/qHSiBkCE7hXHRmHIPgEVwVevVCDjtdoh88sgYG2x68sHvgf3vTq3I+tEVwOkMTzjq4NYZh1tajXMTk5PwO5/tNzvh+sfu+2zAeLYpx9muZo1cqs5AZdr/Kz7YhL5AzcVeDSfbg2SbgaCS6ky1i8+70a23xUEwvnd2R9XCoxCYRN3bnudc3R1dsZtYSQax5fWJxyPzeotXZ6RJNfT4a2s43g4qPs6SKQT2tB6fiwMoY7G0h7N/JsxSH05TmECfX9No84y929fSB1iiRzsmnmKXWE7IEIQi7M1ETUdftMzJWeEBfwqkrvvKcNtmhrlFf/UiuXIYZBpBVAVHpk+Yd81TtQ6qIcNrarQhTlPAXIa0y4IxE2Ri6iX/I2SbneBxMDdfFq0zCC5My0j2xD8QbFvbVgmdU4ajJxx/PBk1wVkN6o88ijDh1o3rE2CwAen4QpDOutE7kRk3uPIPsnZ69EZqZRMHP0tOrVK0bUq2a07qhFcx3JM4cSgmMyk1y3Oqp6PPgvCtyItxRbLd7FQFqD1Zp3aPwPHGjJjWQ6LsaeuXwvcNYPO4A65jNRQcAAg5ekUs0qz50yCxNcuH0/8U5DT2Ef66T1UWC3hpzvZocM/QQaqiD5cYkpl3poNpBIjqOp06AmTK2yU6KA+dznrMDpVcnREFuOsYX4Pfk4kD6FaRk/V15MdGVm3grx9jHFrq2D7gVxQlgWXdsuOJw1K12UVcFHdfda8rvhhH4LidNJ6KhWHfj5RW9F3Wl9fMgRbXKcd4o5kZpYc/hQgNsR8udeEMPjA44K5Js8yE7EXyYHQIP9AfNbZsRLeI7mZxPpQ3LYJml7dsiCyrzbMobmXadspQjb5Nv5QyABZqjbFTeAuJnH2KyyzP1jyiMzFH4Gcwp7jZBKVq6rnU7y00FzM+UIcN0mrAcPNzt4uPxOOgZjJEd9KkyGWNwUsBwANcBsbO0DeRsir/gI4mUaPjRCwSWDoMUOSrXTsx81oYWV/rOf1JPYFhgsitWGeZ7iWwV+/bZHHUDsrCPThx726VbBHcaldZCKMA5nlrlzeBbk7mFe/mK66YPMKtX5GGGEr2b6cm1kFdWLLTlmfiLK8aPX2lIpplVBQWXWWmdbUz0XPtEf0Ft1yDXsiyx73zCgIXsqG0Sl4NQP1Kjbl2pKCYVHqq1BN5PA4cY2zMgxkTXPdLDmMZ917Ot/LnVKbO3foPCQoWWvGaJ+hgbYWxkI97FfjM2n8GbLP0uzK4rThPqrzUmZPSCRKosphJGtPXlILHYvTR87jBqtJxIjyJPq6qtTVssAHfAWWptq9+0nQBZL00PbVcxayA3d8eoijTMD3IkS38uZfoseOmQtYJZxheYLuTxLH0UoqCaa4t5uytsFnFXuTYBOgBHobZTeQMimn1A3VV9Ytd8C+Tlm5hz+OCTJENytu6LLhAh7tBmcuEw+QAp65p137f7rfF3uhX3koeT29bt1VhjZ+BqiaAgj1qqGRN1w8fBIAEe2t1wrE3vnv8OjKB8OEqlRU2ASujZeJRxI48tGb25J2md5pAvneZA7DrN4RFiVIJ/B/nZFFyPh4gVIZPxSk3iO4pA02gM5vvO/bMxn7tcGmCkr37lhviR1QxBZj75KBfygcC0K3GRoDiWXuDQVLnVS3Pr+YkhBOElmzJdaIT/SCTGiimMgcHzVVZ6Sy9EP975tODorzqDMSfSI3IX1ZiHRQrWUt6PBmmPrB0EfFhV3fWQzkRefMCWh8qNLr8x1ctrEpqG7Pl33zrGe33BhJxT9faaL9SJG5Xe2GuiH3rBQskve2W7WcHVYjCvSsuXFXsT9hC34A2jSURKMaj3lZCV4wtQ1mUX8IuLfZgTjcenXHpFuSw4igaEM7phzlT+Z6txffTEoLw7vKxRrgFRFl9mYp2nUQ7XnVTTlcjW4i2S3Sh+eO1vWEX1VKTTYvFZokeWKKj3zfhVqXZ+qBjeKGKxp5/xgsVRjNBRcJ5HC0Qt5DvD0y4y/kg8prxJAchrSo2a/qEoaVAAkS8dxiDP+MZlelLeD86MvJdgCepoF59M9sCSBP2QLOmHpPqvz669NZNlrNqRZXioUulIhLk0hjH1VThqpLvtL4etJvG8g+pGJtcj6KYbJq6cJLlmfC/sHvP+9p/9UyCSYZgG3w8LWt7LBhq7Wd/afF2l81ni0vn5rs+mpJgoPAjHer3+RSJOjXk3Rj1iUqPWQzegIUGy1+LIeBHNHH6khv2AQoPK+yN2H+R0IENjz48yXNgy2213Cu6B3dizBzzG6foKUi64w1M8mE5O6uKIdAsdIpBRLL0m9KkyKPpoZkXN6GFQgfsxfTa5cPPtuCZL+EDRxyWkhytQl2URFxMKjk/DhZrzjxdNl1SDl/r/tunlY+F0emX6SBfZVX2KArlJtsfnwypDH53vSGGw6mFvhzecU1WQt0FR8Hqy6UGWaa1Q6krtq92vIoIfS/znz38BtXx7jA==)

**Comment by JounQin** [comment]
Is that valid syntax for Svelte itself?

**Comment by ptrxyz** [comment]
Hm, good question. :thinking: 
But I just found this: https://github.com/sveltejs/svelte/issues/5403
Could it be that it's not...?

**Comment by ota-meshi** [comment]
Svelte's compiler does not allow TypeScript inside HTML templates.
Please follow https://github.com/sveltejs/svelte/issues/4701.
