### ISSUE TITLE
"parser.parse is not a function" errors with `eslint-plugin-import`

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#312]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.28.0

### What version of `eslint-plugin-svelte` are you using?

2.26.0

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  extends: ["plugin:svelte/recommended", "plugin:import/recommended"],
  plugins: ["svelte3", "@typescript-eslint"],
  ignorePatterns: ["*.cjs"],
  overrides: [
    {
      files: ["*.svelte"],
      parser: "svelte-eslint-parser",
      parserOptions: {
        parser: "@typescript-eslint/parser",
      },
    },
  ],
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 2020,
    project: "tsconfig.json",
    extraFileExtensions: [".svelte"],
  },
  env: {
    browser: true,
    es2017: true,
    node: true,
  },
};
```
</details>

```svelte
<script lang="ts">
    import TopAppBar from '@detachhead/smui-top-app-bar'
</script>
```

### What did you expect to happen?

no errors

### What actually happened?

```
  2:27  error    Parse errors in imported module '@detachhead/smui-top-app-bar': parser.parse is not a function (undefined:undefined)  import/default
  2:27  warning  Parse errors in imported module '@detachhead/smui-top-app-bar': parser.parse is not a function (undefined:undefined)  import/no-named-as-default
  2:27  warning  Parse errors in imported module '@detachhead/smui-top-app-bar': parser.parse is not a function (undefined:undefined)  import/no-named-as-default-member

✖ 3 problems (1 error, 2 warnings)
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/DetachHead/eslint-plugin-svelte-issue

### Additional comments

i'm not sure if this is an issue with `eslint-plugin-svelte` or `eslint-plugin-import`. however this issue did not occur when i was using `eslint-plugin-svelte3` so i'm leaning more towards the former

**Comment by DetachHead** [comment]
turns out it's due to a trailing comma in the `export`s in that module:

```ts
export { Row, Section, Title, FixedAdjust, ProminentFixedAdjust, DenseFixedAdjust, DenseProminentFixedAdjust, ShortFixedAdjust, AutoAdjust, };
```

```
Error while parsing C:\project\node_modules\@detachhead\smui-top-app-bar\package\index.js
Line 12, column 140: Unexpected token
`parseForESLint` from parser `C:\project\node_modules\svelte-eslint-parser\lib\index.js` is invalid and will just be ignored
```

this is valid syntax so it should not cause an error

**Comment by ota-meshi** [comment]
Your config tries to parse the `*.js` file with the svelte parser. This will result in a parse error.
I think you need to add settings to your config like this:

```js
settings: {
  'import/parsers': {
    '@typescript-eslint/parser': [ '.ts', '.tsx', '.cts', '.mts' ],
    'espree': [ '.js', 'jsx', '.cjs', '.mjs' ],
  }
}
```

See the eslint-plugin-import documentation for details.

https://github.com/import-js/eslint-plugin-import#importparsers

**Comment by DetachHead** [comment]
that fixed it, thanks!
