### ISSUE TITLE
`#each` block with single line comment between function call and a component inside it causes eslint to hang

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#330]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.30.0

### What version of `eslint-plugin-svelte` are you using?

2.14.1

### What did you do?

<details>
<summary>Configuration</summary>

n/a, see playground link
</details>

```svelte
{#each a(
//
a) as a}
<A/>{/each}
```

### What did you expect to happen?

eslint finishes checking the code in a timely manner

### What actually happened?

eslint hangs

### Link to **GitHub Repo** with Minimal Reproducible Example

https://ota-meshi.github.io/eslint-plugin-svelte/playground/#eJyrVkrOT0lVslKqVk5NTM5QSNSIydPXj8lL1FRILFZIrI3Js3HUt6vWB0nWKtUCAGG/Dwg=

### Additional comments

- the playground hangs when it tries to check this code
  ![image](https://user-images.githubusercontent.com/57028336/208362855-78c8b943-3ba0-4cb3-ac30-ce22996eba8c.png)
  
  when running `eslint` locally, it hangs forever with no output

- also related: #327
  the only difference is the number of characters in the comment and the component name. while trying to reduce this to a minimal example, the behavior kept changing depending on how many characters each line had

**Comment by ota-meshi** [comment]
Thank you for this issue!
This issue seems to be fixed in https://github.com/ota-meshi/svelte-eslint-parser/pull/262. Previous wrong AST caused an infinite loop within ESLint.
