### ISSUE TITLE
documentation - can't scroll when cursor is in a svelte codeblock

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#331]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

n/a

### What version of `eslint-plugin-svelte` are you using?

n/a

### What did you do?

1. navigate to a page with svelte codeblocks in it, eg. https://ota-meshi.github.io/eslint-plugin-svelte/rules/comment-directive/
2. position your cursor above a codeblock and scroll:
    ![image](https://user-images.githubusercontent.com/57028336/208553568-9b624d23-1101-4fca-a485-5f1f3b659789.png)
3. position your cursor inside a codeblock and scroll:
    ![image](https://user-images.githubusercontent.com/57028336/208553705-02c6f940-ac05-4ff2-82e8-54ddedd46df0.png)

### What did you expect to happen?

scrolling works no matter where the cursor is

### What actually happened?

scrolling only works when the cursor is positioned outside of a codeblock

### Link to **GitHub Repo** with Minimal Reproducible Example

n/a

### Additional comments

tested on firefox and chrome

**Comment by ota-meshi** [comment]
Thank you for posting issue.
We're using MonacoEditor for our codeblock playground, but I can't find any options that solve the problem.
https://microsoft.github.io/monaco-editor/

If anyone knows of options to fix the scrolling issue please let me know.
