### ISSUE TITLE
Add support for eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by marekdedic** [ota-meshi/eslint-plugin-svelte#339]
Hi,
I have both this plugin and [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort/) enabled. However, it seems that the import plugin doesn't run for svelte files - is that something that can be fixed from here (or the accompanying parser package)?

Thanks!

**Comment by baseballyama** [comment]
According to the [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort/) codebase, I think it should work.
So for analyzing more details, could you please create minimum REPL project?

**Comment by ota-meshi** [comment]
I recommend using `import/order` instead (, if someone hasn't fixed eslint-plugin-simple-import-sort).
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

See comments for details.
https://github.com/ota-meshi/eslint-plugin-svelte/issues/199#issuecomment-1302892807

**Comment by baseballyama** [comment]
Oh I just check here and I thought that it should be supported.
https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/src/imports.js#L128-L136

But `extractChunks` function parse only top level nodes, so Svelte files don't supported as you said.
https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/src/imports.js#L56

**Comment by marekdedic** [comment]
Thanks for the quick response, I tried opening an issue with eslint-plugin-simple-import-sort, we'll see...

**Comment by lydell** [comment]
Thanks for all the links and research! Gives me a nice head start fixing this in eslint-plugin-simple-import-sort. Much appreciated!
