### ISSUE TITLE
VS Code linting style blocks in Svelte files with both Stylelint and ESLint

### ISSUE THREAD

**Issue by robinloeffel** [ota-meshi/eslint-plugin-svelte#342]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.32.0

### What version of `eslint-plugin-svelte` are you using?

2.14.1

### What did you do?

<details>
<summary>Configuration</summary>

My VS Code is configured to auto-fix auto-fixable problems on save. This has been done by

1. Enabling VS Code to validate `.svelte` and `.astro` files as instructed [here (Astro)](https://github.com/ota-meshi/eslint-plugin-astro#visual-studio-code), [here (Svelte)](https://github.com/ota-meshi/eslint-plugin-svelte#visual-studio-code) and [here (Stylelint)](https://github.com/ota-meshi/stylelint-config-html#visual-studio-code)
2. Setting `editor.codeActionsOnSave.source.fixAll` to `true` in my `settings.json`

Here my configs:

### `.eslintrc.cjs`
```js
module.exports = {
	root: true,
	parser: "@typescript-eslint/parser",
	extends: [
		"plugin:@typescript-eslint/recommended",
		"plugin:astro/recommended",
		"plugin:svelte/recommended"
	],
	plugins: [ "@typescript-eslint" ],
	rules: {
		...
	},
	globals: {
		...
	},
	overrides: [{
		files: [ "*.astro" ],
		parser: "astro-eslint-parser",
		parserOptions: {
			parser: "@typescript-eslint/parser",
			extraFileExtensions: [ ".astro" ]
		},
		rules: {
			...
		}
	}, {
		files: [ "*.svelte" ],
		parser: "svelte-eslint-parser",
		parserOptions: {
			parser: "@typescript-eslint/parser",
			extraFileExtensions: [ ".svelte" ]
		},
		rules: {
			...
		}
	}],
	ignorePatterns: [
		"src/types/**/*",
		"**/*/*.d.ts"
	]
};
```

### `stylelint.config.cjs`
```js
module.exports = {
	extends: [
		"stylelint-config-standard-scss",
		"stylelint-config-idiomatic-order",
		"stylelint-config-html/astro",
		"stylelint-config-html/svelte"
	],
	rules: {
		...
	}
};

```
</details>

And finally, here is a small reproduction:
```svelte
<script lang="ts">
	export const title: string = 'hey'
</script>

<div class="example">
	{ title }
</div>

<style lang="scss">
	.example {
		color: yellow;
	}



</style>
```

And a quick GIF of what's happening:
![ezgif-1-18583e821e](https://user-images.githubusercontent.com/6851646/213243131-8ab8990a-e07a-4286-aaa4-097e22bfe51c.gif)

### What did you expect to happen?

- I would expect ESLint to add a semicolon to the title prop (configured to do so) in the `script` tag
- I would expect Stylelint to remove the unnecessary new lines (configured to do so) in the `style` tag

### What actually happened?

- ☑️ ESLint adds a semicolon to the title prop
- ☑️ Stylelint removes the unnecessary newlines
- ❌ ESLint deletes lines in the `style` tag, as well, sometimes even the `</style>` line

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/robinloeffel/svelte-eslint-repro

**Comment by ota-meshi** [comment]
Thank you for posting this issue!

However, I could not reproduce the problem using your repository.

Does the same problem occur in your environment using the CLI?

**Comment by ota-meshi** [comment]
Additionally, could you please try to reproduce the problem with which of the following settings?

```json
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true,
        "source.fixAll.stylelint": false,
    }
```



```json
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": false,
        "source.fixAll.stylelint": true,
    }
```

**Comment by robinloeffel** [comment]
Wow, thanks for the fast reply! Sadly, I can also reproduce it on another computer of mine, with just the code in the repro repository.

When only enabling one of the two linters, I see the error still being reported, but not auto-fixed. Example of what happens with ESLint off and Stylelint on.
![Screenshot 2023-01-19 at 11 58 28](https://user-images.githubusercontent.com/6851646/213425360-c8b708ff-7c90-42e6-a18e-03f926450059.png)

Funnily enough, I just discovered that when setting explicitly only ESLint and Stylelint to on, ESLint still reports errors in `style` blocks and fixes them, but not as aggressively. So:
```json
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true,
  },
```
instead of:
```json
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
```

Results in the following behavior:

https://user-images.githubusercontent.com/6851646/213426384-00e90783-146a-40c7-a041-a6b2daf8aedc.mov

Running `yarn eslint src` with
```svelte
<script lang="ts">
  export const title = 'sup';
</script>

<div class="example">
  { title }
</div>

<style lang="scss">
  .example {
    color: yellow;
  }




  
</style>
```

results in the following message:
```
yarn run v1.22.19
warning package.json: No license field
$ /Users/robin/Sites/svelte-eslint-repro/node_modules/.bin/eslint src

/Users/robin/Sites/svelte-eslint-repro/src/example.svelte
  14:1  error  More than 1 blank line not allowed  no-multiple-empty-lines
  17:1  error  Trailing spaces not allowed         no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

And if I run it with the `--fix` flag, yes, ESLint also manipulates the `style` block.

Maybe more context to my setup:
- MacBook Air w/ M2 chip
- macOS v13.1
- node v18.12.1
- VS Code v1.74.3
- VS Code ESLint extension v2.2.6
- VS Code Stylelint extension v1.2.3
- yarn v1.22.19

**Comment by ota-meshi** [comment]
Are you saying that auto-fix will not change `</style>` to `/style>` if you use the following settings?

```json
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true,
  },
```

If so, I think the problem is in the VSCode extensions other than eslint or stylelint you use.
I think you need to use the above settings or find out which VSCode extension you use is causing the problem.

**Comment by robinloeffel** [comment]
That is what I'm saying, yes. So it is actually wanted behavior that ESLint looks at and manipulates the `style` blocks in my Svelte files? If so, I would find that quite counter-intuitive. Since this could really open up Pandora's box for all kinds of inter-op issues between ESLint and Stylelint, no?

**Comment by ota-meshi** [comment]
In my opinion, it makes sense that rules that check source code as text, such as `no-multiple-empty-lines` and `no-trailing-spaces`, should also be valid within `<style>` tags. I think those rules should be consistent across script, html, and style.

> Since this could really open up Pandora's box for all kinds of inter-op issues between ESLint and Stylelint, no?

I wasn't quite sure what that meant. I also maintain eslint-plugin-vue and vscode-stylelint, and it works fine.

**Comment by robinloeffel** [comment]
Alright, good to know!

What I meant by my Pandora's box comment is, that maybe letting ESLint look at other blocks than what it's specifically instructed to do so, as in this case the `typescript` and `svelte` blocks, may lead to unexpected side effects in the future. What if ESLint introduces a new rule on the text level, that interferes with a rule that Stylelint has had for a while, or vice-versa? Things like that.

But if you're aware of that, and every one of us keeps that in mind, I'm fine with that, as well. Especially since you've stated that it hasn't led to any problems with your other packages.

Also, thanks for all your ESLint and Stylelint plugins! I've been having a blast using them so far! 👏🏼

**Comment by ota-meshi** [comment]
Thanks for your comment.

If the eslint rules actually behave in a problematic way, please open a new issue.
In that case we can consider creating an extension rule like the [`svelte/no-inner-declarations`](https://ota-meshi.github.io/eslint-plugin-svelte/rules/no-inner-declarations/) rule or the rules provided by `typescript-eslint`.
