### ISSUE TITLE
Export an all config

### ISSUE THREAD

**Issue by oekazuma** [ota-meshi/eslint-plugin-svelte#369]
### Description

Export an all config that contains the default options for all of the rules (except for deprecated ones).

```js
module.exports = {
  extends: ['plugin:svelte/all'],
}
```

**Comment by ota-meshi** [comment]
Thank you for posting this issue!
We can provide that configuration, but we need to detail what we don't recommend in the documentation.
Like eslint:
https://eslint.org/docs/latest/use/configure/configuration-files#using-eslintall
