### ISSUE TITLE
Typescript transpile target is fixed to ESNext

### ISSUE THREAD

**Issue by ptrxyz** [ota-meshi/eslint-plugin-svelte#374]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.34.0

### What version of `eslint-plugin-svelte` are you using?

2.18.0

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
	root: true,
	parser: '@typescript-eslint/parser',
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:svelte/recommended',
		'plugin:svelte/prettier',
		'prettier'
	],
	plugins: ['@typescript-eslint', 'import'],
	ignorePatterns: ['*.cjs'],
	settings: {
		'import/resolver': [
			{
				typescript: {
					project: ['.svelte-kit/tsconfig.json', './tsconfig.targets.json']
				}
			}
		]
	},
	overrides: [
		{
			files: ['*.ts', '*.tsx'],
			parser: '@typescript-eslint/parser', // 'typescript-eslint-parser-for-extra-files',
			parserOptions: {
				project: './tsconfig.json'
			}
		},
		{
			files: ['*.svelte'],
			parser: 'svelte-eslint-parser',
			parserOptions: {
				parser: '@typescript-eslint/parser', // require('typescript-eslint-parser-for-extra-files'),
				project: './tsconfig.json'
			}
		}
	],
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2020,
		extraFileExtensions: ['.svelte']
	},
	env: {
		browser: true,
		es2017: true,
		node: true
	},
	rules: {
		// Typescript
		'@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
		'@typescript-eslint/consistent-type-assertions': [
			'error',
			{ assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' }
		],
		'@typescript-eslint/naming-convention': [
			'warn',
			{ selector: 'typeLike', format: ['PascalCase'], prefix: ['T', '_'] }
		],
		'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
		'mouse-events-have-key-events': 'off',
		// import
		'import/no-unresolved': [
			'error',
			{ ignore: ['app/stores', 'app/forms', 'app/navigation', 'app/environment'] }
		],
		'import/order': [
			'error',
			{
				alphabetize: { order: 'asc' },
				pathGroups: [
					{
						pattern: '$app/**',
						group: 'external'
					}
					// { pattern: 'app/**', group: 'external' } // app/[stores,forms,navigation,environment]
				],
				groups: [
					'type',
					'external',
					['object', 'builtin', 'internal', 'parent', 'index', 'sibling', 'unknown']
				],
				'newlines-between': 'always'
			}
		],
		// unused-imports
		'no-unused-vars': 'off',
		'@typescript-eslint/no-unused-vars': [
			'warn',
			{
				argsIgnorePattern: '^_',
				varsIgnorePattern: '^_',
				caughtErrorsIgnorePattern: '^_'
			}
		]
	}
};

```
</details>

```svelte
<script lang="ts">
	export class TPerson {
		private _age: number;

		get age() {
			return this._age;
		}

		constructor(public firstName: string, public lastName: string, age: number) {
			this._age = age;
		}
	}
</script>
```

### What did you expect to happen?

I found that in https://github.com/ota-meshi/eslint-plugin-svelte/blob/afaea274969a7da6642beee66d33780400a29a68/src/shared/svelte-compile-warns/transform/typescript.ts#L32 the Typescript compile target is pinned to ESNext.

I suggest that this follows the target specified in `tsconfig.json` or allow the user to specify a different target.

This comes in handy when things like this happen: https://github.com/sveltejs/svelte/issues/6900
If I set the Typescript target to "es2020" in my "tsconfig.json", the bug goes away and `svelte-check` won't complain anymore. However ESLint will still complain.

I know that Svelte probably fixes this specific issue, however it still would make sense to keep the ESLint transpile target aligned with the one specified in tsconfig/eslintrc, since I suspect (correct me if I am wrong) that this might have bigger implications, but this is the one where it came to my attention. Can we fix this?

### What actually happened?

ESLint was throwing a compile error, while svelte-check did not complain.

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/ptrxyz/eslint-plugin-svelte-bug-report

This is the basic SvelteKit template. Please check out, then do this:

- npm i
- npm run check (-> find that everything works nicely)
- npm run lint (-> find a "Unexpected Token" error in ./src/routes/+page.svelte)

**Comment by ptrxyz** [comment]
Maybe it would also be an option to allow to override the TS target using compiler options?

```js
const output = ts.transpileModule(code, {
    reportDiagnostics: false,
    compilerOptions: {
        target: context.parserOptions.target || ts.ScriptTarget.ESNext,     // something like this maybe?
        importsNotUsedAsValues: ts.ImportsNotUsedAsValues.Preserve,
        sourceMap: true,
    },
});
```

**Comment by ptrxyz** [comment]
Reopened for discussion, I closed it by accident.

**Comment by ota-meshi** [comment]
Thank you for posting this issue and opening the PR!

I don't think `context.parserOptions` should be used there.
Can you try if using `context.parserServices.program.getCompilerOptions().target` instead, works for your project?

**Comment by ptrxyz** [comment]
Yes, that does also work. And I share the opinion, it's probably the better approach. I am not familiar with your code, but to test it out, I did this: 

```js
const output = ts.transpileModule(code, {
    reportDiagnostics: false,
    compilerOptions: {
        target: context.parserServices.program.getCompilerOptions().target || ts.ScriptTarget.ESNext,     // something like this maybe?
        importsNotUsedAsValues: ts.ImportsNotUsedAsValues.Preserve,
        sourceMap: true,
    },
});
```

It's just a small thing, but if you would accept this solution and if it helps, let me know and I'll make it a PR.
