### ISSUE TITLE
re-implement typescript-eslint's "no any" rules

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#390]
many of the typescript eslint rules don't seem to recognize svelte-specific things. 

# examples
## events
```svelte
<input
    type="checkbox"
    on:change={(event) => {
        // error: Unsafe assignment of an `any` value. (@typescript-eslint/no-unsafe-assignment)
        const foo = event.currentTarget.checked
    }}
/>
```
here, `event` is typed as `Event & { currentTarget: EventTarget & HTMLInputElement }` but the typescript-eslint plugin thinks it's `any`

## `$$Generic`s
```svelte
<script lang="ts">
    type T = $$Generic<number>

    export let foo: T

    // Unsafe member access .toString on an `any` value. (@typescript-eslint/no-unsafe-member-access)
    // Unsafe call of an `any` typed value. (@typescript-eslint/no-unsafe-call)
    foo.toString()
</script>
```
here, the typescript-eslint plugin does not seem to understand `$$Generic`, so it treats them as `any`. (originally raised https://github.com/sveltejs/language-tools/issues/1780)

**Comment by ota-meshi** [comment]
Thank you for posting the issue.

About event types:
The parser needs to provide better typing when it emits virtual code, but I'm still not sure if I can do that 🤔
https://ota-meshi.github.io/svelte-eslint-parser/virtual-script-code/

About `$$Generic`:
The RFC about `$$Generic` don't seem to have been merged yet.
https://github.com/sveltejs/rfcs/pull/38

I don't want to fully support it yet to avoid a lot of breaking changes.
If you want to support it, we can add it as an experimental feature, but I don't have time to do that.

**Comment by DetachHead** [comment]
> About event types:
> The parser needs to provide better typing when it emits virtual code, but I'm still not sure if I can do that 🤔
> https://ota-meshi.github.io/svelte-eslint-parser/virtual-script-code/

would it be possible to use [`svelte2tsx`](https://www.npmjs.com/package/svelte2tsx) instead of `svelte-eslint-parser`? from my understanding that's what svelte uses for its typescript support which would mean the code eslint checks would be the same as what the svelte compiler checks.

this is the output of `svelte2tsx`  on my example above:

```tsx
/// <reference types="svelte" />
function render() {
    ;async () => {
        {
            svelteHTML.createElement('input', {
                type: 'checkbox',
                'on:change': (event) => {
                    const foo = event.currentTarget.checked
                },
            })
        }
    }
    return { props: /** @type {Record<string, never>} */ {}, slots: {}, events: {} }
}

export default class extends __sveltets_2_createSvelte2TsxComponent(
    __sveltets_2_partial(__sveltets_2_with_any_event(render())),
) {}
```

here, the `svelteHTML.createElement` function correctly infers the type of `event` as `Event & { currentTarget: EventTarget & HTMLInputElement }`

**Comment by ota-meshi** [comment]
> would it be possible to use svelte2tsx instead of svelte-eslint-parser?

I think it is very difficult.

**Comment by DetachHead** [comment]
i found another example where a type is incorrectly considered to be `any` - importing types from other `.svelte` files:

```svelte
<!-- Foo.svelte -->
<script lang="ts" context="module">
    export type Foo = number
</script>
```
```svelte
<!-- Bar.svelte -->
<script lang="ts">
    import type { Foo } from './Foo.svelte'

    const asdf: Foo = 1

    // Unsafe member access .fdsa on an `any` value. (@typescript-eslint/no-unsafe-member-access)
    // Unsafe call of an `any` typed value. (@typescript-eslint/no-unsafe-call)
    asdf.toString()
</script>
```

**Comment by ota-meshi** [comment]
I know it. #298

**Comment by DetachHead** [comment]
another example is the sveltekit API route types that are automatically inferred, but not recognised by typescript-eslint:
```ts
export const GET = async ({ request }) => {
    // request is not any, since it's inferred as Request by sveltekit
    request.headers // error: @typescript-eslint/no-unsafe-member-access
}
```

**Comment by ota-meshi** [comment]
Could you please open another issue to better manage those issues?

**Comment by DetachHead** [comment]
done #413

**Comment by ota-meshi** [comment]
As for `currentTarget`, I think it has been improved.
As for `$$Generic`, I think there is more discussion at https://github.com/ota-meshi/svelte-eslint-parser/issues/306, so please follow that.
