### ISSUE TITLE
re-implement the eslint `prefer-const` rule

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#404]
### Description

the `prefer-const` rule included by default in eslint does not understand reactive statements with curly braces:
```svelte
<script lang="ts">
    let foo: number
    $: {
        foo = 1 // 'foo' is never reassigned. Use 'const' instead. (prefer-const)
    }
</script>

{foo}
```

**Comment by ota-meshi** [comment]
Thank you for the bug report. I think it's probably a parser bug.
